version: "3"
services:
    flask:
        build: ./flask/
        ports:
          - "5000:5000"
        network_mode: "host"
    go:
        build: ./go-http/
        ports:
          - "5000:5000"
        network_mode: "host"
    fibjs:
        build: ./fibjs-http/
        ports:
          - "5000:5000"
        network_mode: "host"
    sanic:
        build: ./sanic/
        ports:
          - "5000:5000"
        network_mode: "host"
    tornado:
        build: ./tornado/
        ports:
          - "5000:5000"
        network_mode: "host"
    asyncio:
        build: ./python-asyncio/
        ports:
          - "5000:5000"
        network_mode: "host"

